# Generated by Django 6.0.6 on 2026-06-09 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('digest_email', models.BooleanField(default=False)),
                ('digest_hour', models.IntegerField(default=8)),
                ('task_notifications', models.BooleanField(default=True)),
                ('attendance_notifications', models.BooleanField(default=True)),
                ('evaluation_notifications', models.BooleanField(default=True)),
                ('fm_notifications', models.BooleanField(default=True)),
                ('equipment_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_reviewed', 'Task Reviewed'), ('task_overdue', 'Task Overdue'), ('logbook_reviewed', 'Logbook Reviewed'), ('evaluation_due', 'Evaluation Due'), ('certificate_issued', 'Certificate Issued'), ('attendance_violation', 'Attendance Violation'), ('geofence_violation', 'Geofence Violation'), ('leave_decision', 'Leave Decision'), ('checkout_update', 'Checkout Update'), ('maintenance_update', 'Maintenance Update'), ('fm_outage', 'FM Station Outage'), ('fm_restored', 'FM Station Restored'), ('emergency_alert', 'Emergency Alert'), ('story_review', 'Story Review'), ('seat_request', 'Seat Request'), ('subscription_expiry', 'Subscription Expiry'), ('wifi_decision', 'Wi-Fi Decision'), ('ticket_update', 'Ticket Update'), ('system', 'System'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
