# Generated by Django 6.0.6 on 2026-06-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fm_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_emergency_alert',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_outage',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_on_restored',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='fm_minimum_severity',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_on_emergency_alert',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_on_outage',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_on_restored',
        ),
    ]
