# Generated by Django 6.0.6 on 2026-06-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_fm_notification_prefs'),
        ('notifications', '0004_restore_fm_notification_fields'),
    ]

    operations = [
    ]
