# Generated by Django 6.0.6 on 2026-06-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_restore_fm_notification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_on_emergency_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_on_outage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_on_restored',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='fm_minimum_severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Suppress FM-related notifications below this severity.', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_on_emergency_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_on_outage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_on_restored',
            field=models.BooleanField(default=False),
        ),
    ]
