# Generated by Django 6.0.6 on 2026-06-20 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_failed_login_attempts_user_locked_until_and_more'),
        ('logbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activation_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to activate'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cohort',
                'verbose_name_plural': 'cohorts',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DepartmentActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('logbooks_created', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_activations_performed', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_activations', to='logbooks.cohort')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_activations', to='accounts.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_department_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'department activation',
                'verbose_name_plural': 'department activations',
                'ordering': ['department__name'],
                'unique_together': {('cohort', 'department')},
            },
        ),
        migrations.AddField(
            model_name='logbook',
            name='department_activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbooks', to='logbooks.departmentactivation'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cohort_schedule_mode', models.CharField(choices=[('auto', 'Auto-split'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='logbooks.program'),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('program', 'sequence')},
        ),
    ]
