# Generated by Django 6.0.6 on 2026-06-18 08:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_orgpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('system_down', 'System Down'), ('fm_outage', 'FM Station Outage'), ('security_breach', 'Security Breach'), ('infrastructure', 'Infrastructure Failure'), ('emergency', 'General Emergency'), ('data_breach', 'Data Breach'), ('fire', 'Fire / Evacuation'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('notified_emails', models.JSONField(blank=True, default=list)),
                ('notified_phones', models.JSONField(blank=True, default=list)),
                ('notification_errors', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='accounts.organisation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlertAcknowledgement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm_report.emergencyalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['acknowledged_at'],
            },
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='acknowledged_by',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_alerts', through='fm_report.EmergencyAlertAcknowledgement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FMStation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(help_text="Broadcast frequency, e.g. '88.3 FM'.", max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('stream_url', models.URLField(blank=True, help_text='Public live-stream URL used for the server-side health check.')),
                ('heartbeat_url', models.URLField(blank=True, help_text='Optional external URL this module pings to verify the transmitter is reachable.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive stations are hidden from dashboards and excluded from heartbeat checks.')),
                ('alert_emails', models.JSONField(blank=True, default=list, help_text='List of email addresses notified on outage/restoration.')),
                ('alert_phones', models.JSONField(blank=True, default=list, help_text='List of E.164 phone numbers notified via SMS.')),
                ('current_status', models.CharField(choices=[('on_air', 'On Air'), ('off_air', 'Off Air'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_timeout_minutes', models.PositiveIntegerField(default=5, help_text='Minutes without a heartbeat before the station is auto-flagged off-air.')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Shared secret transmitter hardware must present when posting a heartbeat.')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_stations', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FMOutage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('down_at', models.DateTimeField(db_index=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('auto_detected', models.BooleanField(default=False)),
                ('alert_sent', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_outages_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_outages_resolved', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['-down_at'],
            },
        ),
        migrations.CreateModel(
            name='FMHeartbeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='related_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='fm_report.fmstation'),
        ),
        migrations.CreateModel(
            name='ProgrammeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for the schedule grid, e.g. #3b82f6.', max_length=7)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_slots', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TransmitterReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('forward_power_watts', models.FloatField(blank=True, null=True)),
                ('reflected_power_watts', models.FloatField(blank=True, null=True)),
                ('vswr', models.FloatField(blank=True, help_text='Voltage Standing Wave Ratio — values above ~1.5 typically indicate an antenna/feedline fault.', null=True)),
                ('pa_temperature_celsius', models.FloatField(blank=True, null=True)),
                ('ambient_temperature_celsius', models.FloatField(blank=True, null=True)),
                ('audio_level_db', models.FloatField(blank=True, null=True)),
                ('signal_strength_dbm', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='fm_report.fmstation')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('station_created', 'Station Created'), ('station_updated', 'Station Updated'), ('station_deleted', 'Station Deactivated'), ('outage_reported', 'Outage Reported'), ('outage_restored', 'Outage Restored'), ('alert_triggered', 'Emergency Alert Triggered'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('schedule_updated', 'Schedule Updated'), ('role_changed', 'User Role Changed'), ('notification_prefs_updated', 'Notification Preferences Updated')], db_index=True, max_length=50)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable label for the affected object, e.g. station name.', max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_audit_log', to='accounts.organisation')),
            ],
            options={
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'created_at'], name='fm_report_a_organis_5d2209_idx'), models.Index(fields=['action'], name='fm_report_a_action_06d866_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emergencyalertacknowledgement',
            constraint=models.UniqueConstraint(fields=('alert', 'user'), name='uniq_ack_per_user_per_alert'),
        ),
        migrations.AddIndex(
            model_name='fmstation',
            index=models.Index(fields=['organisation', 'is_active'], name='fm_report_f_organis_0ba12c_idx'),
        ),
        migrations.AddIndex(
            model_name='fmstation',
            index=models.Index(fields=['current_status'], name='fm_report_f_current_bca7bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='fmstation',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_station_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='fmoutage',
            index=models.Index(fields=['station', 'restored_at'], name='fm_report_f_station_485561_idx'),
        ),
        migrations.AddIndex(
            model_name='fmoutage',
            index=models.Index(fields=['down_at'], name='fm_report_f_down_at_41de94_idx'),
        ),
        migrations.AddIndex(
            model_name='fmoutage',
            index=models.Index(fields=['severity'], name='fm_report_f_severit_c854b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='fmoutage',
            constraint=models.UniqueConstraint(condition=models.Q(('restored_at__isnull', True)), fields=('station',), name='uniq_open_outage_per_station'),
        ),
        migrations.AddConstraint(
            model_name='fmoutage',
            constraint=models.CheckConstraint(condition=models.Q(('restored_at__isnull', True), ('restored_at__gte', models.F('down_at')), _connector='OR'), name='restored_at_after_down_at'),
        ),
        migrations.AddIndex(
            model_name='fmheartbeat',
            index=models.Index(fields=['station', 'received_at'], name='fm_report_f_station_41e084_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['organisation', 'resolved'], name='fm_report_e_organis_052f50_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['severity'], name='fm_report_e_severit_9584cd_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeslot',
            index=models.Index(fields=['station', 'weekday'], name='fm_report_p_station_e55393_idx'),
        ),
        migrations.AddConstraint(
            model_name='programmeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='programme_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='transmitterreading',
            index=models.Index(fields=['station', 'recorded_at'], name='fm_report_t_station_a4cc01_idx'),
        ),
    ]
