"""
Nexus — Attachee Bulk Import & Management Views
Handles: bulk CSV/Excel import with role-scoped restrictions,
         supervisor assignment/deassignment, account toggle,
         auto-generated passwords, welcome emails.

NOTE: employee_id is auto-generated by a DB-level trigger
(generate_employee_id()) based on NEW.is_staff, using the
employee_id_seq sequence. Do NOT set employee_id in Python —
leave it out of create_user() calls entirely.
"""
import io
import csv
import secrets
import string
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from rest_framework import status
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from rest_framework.views import APIView

try:
    import openpyxl
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False

User = get_user_model()  # type: ignore[assignment]  # custom model with UserManager

# ── Constants ─────────────────────────────────────────────────────────────────

REQUIRED_COLS = {'email', 'first_name', 'last_name'}

# ── Password generator ────────────────────────────────────────────────────────

def _generate_password(length: int = 12) -> str:
    """
    Generates a secure random password that satisfies common validation rules:
    at least one uppercase, one lowercase, one digit, one special character.
    """
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    while True:
        pwd = ''.join(secrets.choice(alphabet) for _ in range(length))
        if (
            any(c.isupper() for c in pwd)
            and any(c.islower() for c in pwd)
            and any(c.isdigit() for c in pwd)
            and any(c in "!@#$%^&*" for c in pwd)
        ):
            return pwd


# ── File parsers ──────────────────────────────────────────────────────────────

def _normalize_row(row: dict) -> dict:
    return {k.strip().lower(): str(v).strip() for k, v in row.items() if v is not None}


def _rows_from_csv(file_bytes: bytes) -> list:
    decoded = file_bytes.decode('utf-8-sig')
    reader = csv.DictReader(io.StringIO(decoded))
    return [_normalize_row(r) for r in reader]


def _rows_from_xlsx(file_bytes: bytes) -> list:
    if not OPENPYXL_AVAILABLE:
        raise ValueError("openpyxl is not installed; only CSV is supported.")
    wb = openpyxl.load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []
    headers = [str(h).strip().lower() if h else '' for h in rows[0]]
    result = []
    for row in rows[1:]:
        if not any(row):
            continue
        result.append(_normalize_row(dict(zip(headers, [v for v in row]))))
    return result


def _parse_file(uploaded_file) -> list:
    name = uploaded_file.name.lower()
    data = uploaded_file.read()
    if name.endswith('.csv'):
        return _rows_from_csv(data)
    if name.endswith(('.xlsx', '.xls')):
        return _rows_from_xlsx(data)
    raise ValueError("Unsupported file type. Upload a .csv or .xlsx file.")


# ── Welcome email ─────────────────────────────────────────────────────────────

def _send_welcome_email(user_obj, raw_password: str, org_name: str, frontend_url: str):
    """
    Sends a welcome / credential email to a newly created user.
    Failures are swallowed so they never block account creation.
    """
    try:
        from django.core.mail import send_mail
        dept_name = user_obj.department.name if user_obj.department else 'your department'
        role_display = user_obj.get_role_display() if hasattr(user_obj, 'get_role_display') else user_obj.role
        subject = f"Welcome to {org_name} — Your Account is Ready"
        message = (
            f"Hi {user_obj.first_name},\n\n"
            f"An account has been created for you on the {org_name} portal.\n\n"
            f"  Role:              {role_display}\n"
            f"  Department:        {dept_name}\n"
            f"  Email / Username:  {user_obj.email}\n"
            f"  Employee ID:       {user_obj.employee_id or '—'}\n"
            f"  Temporary Password: {raw_password}\n\n"
            f"You must change your password the first time you log in.\n\n"
            f"  Login: {frontend_url}/login\n\n"
            f"If you did not expect this email, contact your system administrator.\n\n"
            f"— {org_name} Team"
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=None,   # uses DEFAULT_FROM_EMAIL from settings
            recipient_list=[user_obj.email],
            fail_silently=True,
        )
    except Exception:
        pass


# ── Bulk Import ───────────────────────────────────────────────────────────────

class AttacheeBulkImportView(APIView):
    """
    POST /attachees/bulk-import/

    Accepts a CSV or XLSX file. The ONLY required columns are:
        email, first_name, last_name

    Optional columns (anything extra is ignored):
        phone, employee_id, department, branch, role

    Password is ALWAYS auto-generated by the server — any password column
    in the CSV is ignored. Employee ID is auto-generated by a DB trigger
    (see generate_employee_id()) based on is_staff — never set in Python.

    Role rules:
      - system_admin / hr_officer → can import into any dept/branch in their org
      - department_leader         → only their own department & branch
    """
    parser_classes = [MultiPartParser]

    ALLOWED_ROLES = {'system_admin', 'hr_officer', 'department_leader', 'executive'}

    def post(self, request):
        caller = request.user
        caller_role = getattr(caller, 'role', '')

        if caller_role not in self.ALLOWED_ROLES:
            return Response(
                {'detail': 'Only HR officers, system admins, and department leaders may bulk-import.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        uploaded = request.FILES.get('file')
        if not uploaded:
            return Response({'detail': 'No file provided.'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            rows = _parse_file(uploaded)
        except ValueError as exc:
            return Response({'detail': str(exc)}, status=status.HTTP_400_BAD_REQUEST)

        if not rows:
            return Response(
                {'detail': 'File is empty or has no data rows.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # Validate required columns
        headers = set(rows[0].keys())
        missing = REQUIRED_COLS - headers
        if missing:
            return Response(
                {'detail': f"Missing required columns: {', '.join(sorted(missing))}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        from django.conf import settings
        frontend_url = getattr(settings, 'FRONTEND_URL', 'http://localhost:5173')
        org_name = caller.organisation.name if caller.organisation else 'Nexus'

        caller_branch = caller.branch
        caller_dept = caller.department

        created, skipped, duplicates, errors = [], [], [], []

        for i, row in enumerate(rows, start=2):  # row 1 = header
            email = row.get('email', '').lower().strip()
            if not email:
                errors.append({'row': i, 'email': '', 'reason': 'Missing email.'})
                continue

            # ── Resolve department ────────────────────────────────────────────
            row_dept_raw = row.get('department', '').strip()
            row_branch_raw = row.get('branch', '').strip()
            resolved_dept = caller_dept
            resolved_branch = caller_branch

            if row_dept_raw:
                from apps.accounts.models import Department
                dept_qs = Department.objects.filter(organisation=caller.organisation)
                dept = dept_qs.filter(name__iexact=row_dept_raw).first()
                if dept is None:
                    skipped.append({
                        'row': i, 'email': email,
                        'reason': f"Department '{row_dept_raw}' not found in your organisation.",
                    })
                    continue
                if caller_role == 'department_leader' and dept != caller_dept:
                    skipped.append({
                        'row': i, 'email': email,
                        'reason': f"Department '{dept.name}' is outside your scope.",
                    })
                    continue
                resolved_dept = dept

            if row_branch_raw:
                from apps.accounts.models import Branch
                branch_qs = Branch.objects.filter(organisation=caller.organisation)
                branch = branch_qs.filter(name__iexact=row_branch_raw).first()
                if branch is None:
                    skipped.append({
                        'row': i, 'email': email,
                        'reason': f"Branch '{row_branch_raw}' not found in your organisation.",
                    })
                    continue
                if caller_role == 'department_leader' and branch != caller_branch:
                    skipped.append({
                        'row': i, 'email': email,
                        'reason': f"Branch '{branch.name}' is outside your scope.",
                    })
                    continue
                resolved_branch = branch

            # ── Duplicate check ───────────────────────────────────────────────
            existing = User.objects.filter(email=email).first()
            if existing:
                duplicates.append({
                    'row': i,
                    'email': email,
                    'full_name': existing.get_full_name(),
                    'department': existing.department.name if existing.department else None,
                    'branch': existing.branch.name if existing.branch else None,
                    'is_active': existing.is_active,
                    'date_joined': existing.date_joined.isoformat() if existing.date_joined else None,
                    'message': 'An account with this email already exists.',
                })
                continue

            # ── Create user ───────────────────────────────────────────────────
            # Password is server-generated. employee_id is NOT set here —
            # the DB trigger generate_employee_id() assigns it based on
            # is_staff (False for attachees -> 'INTERN-<n>').
            raw_password = _generate_password()

            first_name = row.get('first_name', '').strip()
            last_name = row.get('last_name', '').strip()
            phone = row.get('phone', '').strip()

            try:
                new_user = User.objects.create_user(  # type: ignore[call-arg]
                    email,           # positional — matches UserManager.create_user(self, email, …)
                    raw_password,
                    first_name=first_name,
                    last_name=last_name,
                    phone=phone,
                    role='attachee',
                    is_staff=False,
                    organisation=caller.organisation,
                    branch=resolved_branch,
                    department=resolved_dept,
                    must_change_password=True,
                )
                new_user.refresh_from_db()  # pick up employee_id set by DB trigger

                # Send welcome email with credentials
                _send_welcome_email(new_user, raw_password, org_name, frontend_url)

                created.append({
                    'email': new_user.email,
                    'full_name': new_user.get_full_name(),
                    'employee_id': new_user.employee_id,
                    'department': new_user.department.name if new_user.department else None,
                    'branch': new_user.branch.name if new_user.branch else None,
                })

            except IntegrityError as exc:
                errors.append({'row': i, 'email': email, 'reason': str(exc)})
            except Exception as exc:
                errors.append({'row': i, 'email': email, 'reason': str(exc)})

        overall_status = status.HTTP_201_CREATED if created else status.HTTP_400_BAD_REQUEST
        return Response({
            'summary': {
                'created':    len(created),
                'duplicates': len(duplicates),
                'skipped':    len(skipped),
                'errors':     len(errors),
            },
            'created':    created[:50],
            'duplicates': duplicates[:50],
            'skipped':    skipped[:50],
            'errors':     errors[:50],
        }, status=overall_status)


# ── Template Download ─────────────────────────────────────────────────────────

class BulkImportTemplateView(APIView):
    """
    GET /attachees/bulk-import/template/
    Returns a minimal CSV template. Password/EmployeeID columns are
    intentionally OMITTED — they are auto-generated by the server / DB trigger.
    """
    def get(self, request):
        from django.http import HttpResponse
        lines = [
            # Only the columns HR actually needs to fill in
            'email,first_name,last_name,phone,department,branch',
            'jane.doe@example.com,Jane,Doe,+254700000001,Engineering,Nairobi HQ',
            'john.smith@example.com,John,Smith,+254700000002,Marketing,Mombasa Branch',
        ]
        content = '\n'.join(lines)
        response = HttpResponse(content, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="attachee_import_template.csv"'
        return response


# ── Single-user Create (used by Add Attachee / Add Staff modals) ──────────────

class CreateUserWithCredentialsView(APIView):
    """
    POST /attachees/create/   (or /accounts/users/create/ — mount wherever fits)

    Body (JSON):
        first_name*, last_name*, email*, role, phone, department, branch

    The server:
      1. Auto-generates a secure password
      2. Lets the DB trigger auto-generate a unique Employee ID
         (based on is_staff — never set employee_id here)
      3. Sets must_change_password = True
      4. Emails the credentials to the new user
      5. Returns the generated employee_id and temp_password so HR can
         copy them from the success screen if needed.
    """
    ALLOWED_ROLES = {'system_admin', 'hr_officer', 'department_leader', 'executive'}

    # Roles that should be treated as staff (affects DB trigger's prefix choice)
    STAFF_ROLES = {'system_admin', 'hr_officer', 'department_leader', 'executive', 'supervisor'}

    def post(self, request):
        caller = request.user
        if getattr(caller, 'role', '') not in self.ALLOWED_ROLES:
            return Response({'detail': 'Permission denied.'}, status=status.HTTP_403_FORBIDDEN)

        data = request.data
        email = (data.get('email') or '').strip().lower()
        first_name = (data.get('first_name') or '').strip()
        last_name = (data.get('last_name') or '').strip()

        if not email or not first_name:
            return Response(
                {'detail': 'email and first_name are required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if User.objects.filter(email=email).exists():
            return Response(
                {'detail': 'A user with this email already exists.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # Resolve optional FK fields
        department = None
        branch = None
        dept_id = data.get('department')
        branch_id = data.get('branch')

        if dept_id:
            from apps.accounts.models import Department
            department = Department.objects.filter(
                id=dept_id, organisation=caller.organisation
            ).first()

        if branch_id:
            from apps.accounts.models import Branch
            branch = Branch.objects.filter(
                id=branch_id, organisation=caller.organisation
            ).first()

        # Prevent privilege escalation
        role = (data.get('role') or 'attachee').strip()
        if caller.role == 'department_leader':
            role = 'attachee'  # dept leaders can only create attachees

        is_staff = role in self.STAFF_ROLES

        raw_password = _generate_password()

        from django.conf import settings
        frontend_url = getattr(settings, 'FRONTEND_URL', 'http://localhost:5173')
        org_name = caller.organisation.name if caller.organisation else 'Nexus'

        try:
            # Positional args match our custom UserManager.create_user(email, password, **extra)
            new_user = User.objects.create_user(  # type: ignore[call-arg]
                email,
                raw_password,
                first_name=first_name,
                last_name=(last_name or ''),
                phone=(data.get('phone') or '').strip(),
                role=role,
                is_staff=is_staff,
                organisation=caller.organisation,
                branch=branch or caller.branch,
                department=department or caller.department,
                must_change_password=True,
            )
            new_user.refresh_from_db()  # pick up employee_id set by DB trigger

            _send_welcome_email(new_user, raw_password, org_name, frontend_url)

            return Response({
                'id': str(new_user.pk),
                'email': new_user.email,
                'full_name': new_user.get_full_name(),
                'first_name': new_user.first_name,
                'last_name': new_user.last_name,
                'employee_id': new_user.employee_id,
                'temp_password': raw_password,   # shown once in the UI, not stored
                'role': new_user.role,
                'must_change_password': True,
            }, status=status.HTTP_201_CREATED)

        except IntegrityError as exc:
            return Response({'detail': str(exc)}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as exc:
            return Response({'detail': str(exc)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


# ── Supervisor Assignment ─────────────────────────────────────────────────────

class AssignSupervisorView(APIView):
    """POST /attachees/<uuid:pk>/assign-supervisor/"""

    ALLOWED_ROLES = {'department_leader', 'system_admin', 'hr_officer', 'executive'}

    def post(self, request, pk):
        caller = request.user
        if caller.role not in self.ALLOWED_ROLES:
            return Response({'detail': 'Permission denied.'}, status=status.HTTP_403_FORBIDDEN)

        try:
            attachee = User.objects.get(pk=pk, role='attachee', organisation=caller.organisation)
        except User.DoesNotExist:
            return Response({'detail': 'Attachee not found.'}, status=status.HTTP_404_NOT_FOUND)

        if caller.role == 'department_leader' and attachee.department != caller.department:
            return Response(
                {'detail': 'Attachee is not in your department.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        supervisor_id = request.data.get('supervisor_id')
        if not supervisor_id:
            return Response(
                {'detail': 'supervisor_id is required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            supervisor = User.objects.get(
                pk=supervisor_id, role='supervisor', organisation=caller.organisation,
            )
        except User.DoesNotExist:
            return Response(
                {'detail': 'Supervisor not found in your organisation.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        if caller.role == 'department_leader' and supervisor.department != caller.department:
            return Response(
                {'detail': 'Supervisor is not in your department.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        if hasattr(attachee, 'supervisor_user'):
            attachee.supervisor_user = supervisor
            attachee.save(update_fields=['supervisor_user'])

        return Response({
            'detail': 'Supervisor assigned successfully.',
            'attachee': {'id': str(attachee.pk), 'full_name': attachee.get_full_name()},
            'supervisor': {'id': str(supervisor.pk), 'full_name': supervisor.get_full_name()},
        })


class DeassignSupervisorView(APIView):
    """POST /attachees/<uuid:pk>/deassign-supervisor/"""

    ALLOWED_ROLES = {'department_leader', 'system_admin', 'hr_officer', 'executive'}

    def post(self, request, pk):
        caller = request.user
        if caller.role not in self.ALLOWED_ROLES:
            return Response({'detail': 'Permission denied.'}, status=status.HTTP_403_FORBIDDEN)

        try:
            attachee = User.objects.get(pk=pk, role='attachee', organisation=caller.organisation)
        except User.DoesNotExist:
            return Response({'detail': 'Attachee not found.'}, status=status.HTTP_404_NOT_FOUND)

        if caller.role == 'department_leader' and attachee.department != caller.department:
            return Response(
                {'detail': 'Attachee is not in your department.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        if hasattr(attachee, 'supervisor_user'):
            attachee.supervisor_user = None
            attachee.save(update_fields=['supervisor_user'])

        return Response({'detail': 'Supervisor removed successfully.'})


# ── Toggle Active ─────────────────────────────────────────────────────────────

class ToggleAttacheeActiveView(APIView):
    """POST /attachees/<uuid:pk>/toggle-active/  Body: { "is_active": bool }"""

    ALLOWED_ROLES = {'department_leader', 'system_admin', 'hr_officer', 'executive'}

    def post(self, request, pk):
        caller = request.user
        if caller.role not in self.ALLOWED_ROLES:
            return Response({'detail': 'Permission denied.'}, status=status.HTTP_403_FORBIDDEN)

        try:
            attachee = User.objects.get(pk=pk, role='attachee', organisation=caller.organisation)
        except User.DoesNotExist:
            return Response({'detail': 'Attachee not found.'}, status=status.HTTP_404_NOT_FOUND)

        if caller.role == 'department_leader' and attachee.department != caller.department:
            return Response(
                {'detail': 'Attachee is not in your department.'},
                status=status.HTTP_403_FORBIDDEN,
            )

        new_state = request.data.get('is_active')
        if new_state is None:
            return Response(
                {'detail': 'is_active field is required.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        attachee.is_active = bool(new_state)
        attachee.save(update_fields=['is_active'])

        action = 'activated' if attachee.is_active else 'deactivated'
        return Response({
            'detail': f'Attachee account {action} successfully.',
            'id': str(attachee.pk),
            'is_active': attachee.is_active,
        })
    