# Generated by Django 6.0.6 on 2026-06-16 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_must_change_password'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
