# Generated by Django 6.0.6 on 2026-06-17 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_maintenancelog_departments_maintenancelog_is_bulk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
