# Generated by Django 6.0.6 on 2026-06-16 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Swahilipot FM', max_length=120, unique=True)),
                ('frequency_mhz', models.DecimalField(decimal_places=3, help_text='Numeric value of the frequency (MHz / kHz). Use 0 for online streams.', max_digits=8)),
                ('band', models.CharField(choices=[('FM', 'FM'), ('AM', 'AM'), ('DAB', 'DAB'), ('SW', 'Short Wave'), ('LW', 'Long Wave'), ('OL', 'Online / Stream')], default='FM', max_length=4)),
                ('stream_url', models.URLField(blank=True, help_text='Live stream URL if applicable')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frequency',
                'verbose_name_plural': 'Frequencies',
                'ordering': ['band', 'frequency_mhz'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('show_type', models.CharField(choices=[('news', 'News'), ('music', 'Music'), ('talk', 'Talk'), ('sport', 'Sport'), ('drama', 'Drama'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='radio/shows/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadioSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('show_name', models.CharField(editable=False, max_length=200)),
                ('frequency_name', models.CharField(editable=False, max_length=120)),
                ('presenter_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('show_type', models.CharField(blank=True, editable=False, max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g. Studio A', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('show_plan', models.TextField(blank=True, help_text='Submitted by presenter before air-time')),
                ('reminded_30min', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='radio.frequency')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_slots', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='radio.show')),
            ],
            options={
                'verbose_name': 'Radio Slot',
                'verbose_name_plural': 'Radio Slots',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='radio_radio_start_d_1ad380_idx'), models.Index(fields=['presenter', 'start_datetime'], name='radio_radio_present_972870_idx'), models.Index(fields=['status'], name='radio_radio_status_b6c641_idx')],
            },
        ),
    ]
