# Generated by Django 6.0.6 on 2026-06-11 07:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.CharField(choices=[('completion', 'Certificate of Completion'), ('recommendation', 'Recommendation Letter'), ('achievement', 'Achievement Award'), ('participation', 'Participation Certificate')], default='completion', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('qr_verification_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, max_length=200)),
                ('signed_by_title', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('awarded_date', models.DateField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_badges', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['organisation', 'status'], name='certificate_organis_6f0307_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['qr_verification_code'], name='certificate_qr_veri_7c395d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_cd0c46_idx'),
        ),
    ]
