# Generated by Django 6.0.6 on 2026-06-12 01:27

import apps.filetransfer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetransfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.filetransfer.models.upload_to),
        ),
    ]
