# Generated by Django 6.0.6 on 2026-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor_user',
        ),
        migrations.AddField(
            model_name='user',
            name='font_preference',
            field=models.CharField(choices=[('default', 'Default'), ('dyslexic', 'Dyslexic-friendly'), ('mono', 'Monospace'), ('serif', 'Serif')], default='default', help_text='UI font selected by the user in Accessibility settings', max_length=20),
        ),
    ]
