# Generated by Django 6.0.6 on 2026-06-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mfa_email_fields'),
        ('accounts', '0003_remove_user_supervisor_user_user_font_preference'),
    ]

    operations = [
    ]
