# Generated by Django 6.0.6 on 2026-06-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260615_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', help_text='UI language selected by the user in Accessibility settings', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_email_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
