# Generated by Django 6.0.6 on 2026-06-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_preference_alter_user_mfa_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_email_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
