# Generated by Django 6.0.6 on 2026-06-17 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_leave_days', models.PositiveIntegerField(default=21)),
                ('sick_leave_days', models.PositiveIntegerField(default=14)),
                ('maternity_leave_days', models.PositiveIntegerField(default=90)),
                ('paternity_leave_days', models.PositiveIntegerField(default=14)),
                ('probation_weeks', models.PositiveIntegerField(default=12)),
                ('notice_weeks', models.PositiveIntegerField(default=4)),
                ('default_stipend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_policy', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Organisation HR Policy',
            },
        ),
    ]
