// Nexus — Attachee Management (full-featured)
// Bulk import: password & employee ID are auto-generated by backend.
// "Add Attachee" opens an inline onboard modal — credentials shown on success.
import { useState, useRef, useCallback, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { format, parseISO } from "date-fns";
import {
	GraduationCap,
	Search,
	Eye,
	UserPlus,
	Download,
	BarChart3,
	Upload,
	X,
	CheckCircle,
	CheckCircle2,
	AlertCircle,
	Info,
	UserCheck,
	UserX,
	ShieldCheck,
	ShieldOff,
	FileSpreadsheet,
	Loader2,
	AlertTriangle,
	RefreshCw,
	Mail,
	Filter,
	Users,
	SquareCheck,
	Square,
	Shield,
	Phone,
	Copy,
} from "lucide-react";
import { usersApi, hrApi, api } from "../../services/api";
import { useAuthStore } from "../../services/api";
import clsx from "clsx";
import toast from "react-hot-toast";
import { Link } from "react-router-dom";


// ── Types ─────────────────────────────────────────────────────────────────────

interface Attachee {
	id: string;
	full_name: string;
	email: string;
	employee_id?: string;
	department?: string;
	department_name?: string;
	branch_name?: string;
	is_active: boolean;
	date_joined?: string;
	last_login?: string;
	phone?: string;
	supervisor_user?: string;
	supervisor_name?: string;
}

interface Supervisor {
	id: string;
	full_name: string;
	email: string;
	department_name?: string;
}

interface Department {
	id: string;
	name: string;
}

interface Branch {
	id: string;
	name: string;
}

// A parsed row from the CSV — not yet saved
interface PreviewRow {
	_rowIndex: number;
	email: string;
	first_name: string;
	last_name: string;
	full_name: string;
	phone?: string;
	department?: string;
	branch?: string;
	// validation
	status: "valid" | "duplicate" | "invalid";
	statusReason?: string;
}

interface ImportResult {
	summary: {
		created: number;
		duplicates: number;
		skipped: number;
		errors: number;
	};
	created: {
		email: string;
		full_name: string;
		employee_id?: string;
		department?: string;
		branch?: string;
	}[];
	duplicates: {
		row: number;
		email: string;
		full_name?: string;
		department?: string;
		is_active?: boolean;
		date_joined?: string;
		message: string;
	}[];
	skipped: { row: number; email: string; reason: string }[];
	errors: { row: number; email: string; reason: string }[];
}

// Created-user credentials (shown once after Add Attachee)
interface CreatedCredentials {
	full_name: string;
	email: string;
	employee_id: string;
	temp_password: string;
}

// ── CSV parser (client-side preview) ─────────────────────────────────────────
// NOTE: password / employee_id columns are intentionally NOT parsed —
// they are always auto-generated by the backend.

function parseCSVText(text: string): Record<string, string>[] {
	const lines = text.split(/\r?\n/).filter(Boolean);
	if (lines.length < 2) return [];
	const headers = lines[0]
		.split(",")
		.map((h) => h.trim().toLowerCase().replace(/^"|"$/g, ""));
	return lines.slice(1).map((line) => {
		const vals = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
		const row: Record<string, string> = {};
		headers.forEach((h, i) => {
			row[h] = vals[i] ?? "";
		});
		return row;
	});
}

async function parseFilePreview(file: File): Promise<PreviewRow[]> {
	return new Promise((resolve, reject) => {
		const reader = new FileReader();
		reader.onload = (e) => {
			try {
				const text = e.target?.result as string;
				const rawRows = parseCSVText(text);
				const seen = new Set<string>();
				const rows: PreviewRow[] = rawRows.map((r, i) => {
					const email = (r.email ?? "").toLowerCase().trim();
					const firstName = (r.first_name ?? r.firstname ?? "").trim();
					const lastName = (r.last_name ?? r.lastname ?? "").trim();

					let status: PreviewRow["status"] = "valid";
					let statusReason: string | undefined;

					if (!email) {
						status = "invalid";
						statusReason = "Missing email";
					} else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
						status = "invalid";
						statusReason = "Invalid email format";
					} else if (!firstName) {
						status = "invalid";
						statusReason = "Missing first name";
					} else if (seen.has(email)) {
						status = "duplicate";
						statusReason = "Duplicate email in file";
					} else {
						seen.add(email);
					}

					return {
						_rowIndex: i + 2,
						email,
						first_name: firstName,
						last_name: lastName,
						full_name: `${firstName} ${lastName}`.trim(),
						phone: r.phone?.trim(),
						department: r.department?.trim(),
						branch: r.branch?.trim(),
						status,
						statusReason,
					};
				});
				resolve(rows);
			} catch (err) {
				reject(err);
			}
		};
		reader.onerror = () => reject(new Error("Could not read file"));
		reader.readAsText(file);
	});
}

// ── API helpers ───────────────────────────────────────────────────────────────

const attacheeApi = {
	/**
	 * Sends only the required fields (email, first_name, last_name, phone?,
	 * department?, branch?) — password and employee_id are auto-generated
	 * by the backend and emailed to the user.
	 */
	commitImport: async (rows: PreviewRow[]): Promise<ImportResult> => {
		const header = "email,first_name,last_name,phone,department,branch";
		const lines = rows.map((r) =>
			[
				r.email,
				r.first_name,
				r.last_name,
				r.phone ?? "",
				r.department ?? "",
				r.branch ?? "",
			]
				.map((v) => `"${String(v).replace(/"/g, '""')}"`)
				.join(","),
		);
		const csvContent = [header, ...lines].join("\n");
		const blob = new Blob([csvContent], { type: "text/csv" });
		const file = new File([blob], "import.csv", { type: "text/csv" });
		const fd = new FormData();
		fd.append("file", file);
		const res = await api.post("attachees/bulk-import/", fd, {
			headers: { "Content-Type": "multipart/form-data" },
		});
		return res.data;
	},

	downloadTemplate: () => {
		window.open("/api/v1/attachees/bulk-import/template/", "_blank");
	},

	/**
	 * Single-user creation — backend auto-generates password + employee_id
	 * and emails the credentials.
	 */
	createAttachee: async (payload: {
		first_name: string;
		last_name: string;
		email: string;
		phone?: string;
		department?: string;
		branch?: string;
	}): Promise<CreatedCredentials> => {
		const res = await api.post("attachees/create/", payload);
		const d = res.data;
		return {
			full_name: d.full_name || `${d.first_name} ${d.last_name}`,
			email: d.email,
			employee_id: d.employee_id || "—",
			temp_password: d.temp_password || "Sent via email",
		};
	},

	assignSupervisor: async (attacheeId: string, supervisorId: string) => {
		const res = await api.post(`/attachees/${attacheeId}/assign-supervisor/`, {
			supervisor_id: supervisorId,
		});
		return res.data;
	},

	deassignSupervisor: async (attacheeId: string) => {
		const res = await api.post(`/attachees/${attacheeId}/deassign-supervisor/`);
		return res.data;
	},

	toggleActive: async (attacheeId: string, isActive: boolean) => {
		const res = await api.post(`/attachees/${attacheeId}/toggle-active/`, {
			is_active: isActive,
		});
		return res.data;
	},
};

// ── Credential display card ───────────────────────────────────────────────────

function CredentialRow({
	label,
	value,
	mono = false,
}: {
	label: string;
	value: string;
	mono?: boolean;
}) {
	const copy = () => {
		navigator.clipboard.writeText(value);
		toast.success(`${label} copied`);
	};
	return (
		<div className="flex items-center justify-between p-3 bg-surface rounded-xl border border-white/5 gap-3">
			<div className="min-w-0">
				<div className="text-[10px] text-slate-500 uppercase tracking-wide mb-0.5">
					{label}
				</div>
				<div
					className={clsx(
						"text-sm text-white font-medium truncate",
						mono && "font-mono",
					)}>
					{value}
				</div>
			</div>
			<button
				onClick={copy}
				className="btn-ghost btn-sm p-1.5 text-slate-400 hover:text-white shrink-0"
				title={`Copy ${label}`}>
				<Copy size={13} />
			</button>
		</div>
	);
}

// ── Add Attachee Modal ────────────────────────────────────────────────────────

function AddAttacheeModal({
	departments,
	branches,
	onClose,
}: {
	departments: Department[];
	branches: Branch[];
	onClose: () => void;
}) {
	const qc = useQueryClient();
	const [form, setForm] = useState({
		first_name: "",
		last_name: "",
		email: "",
		phone: "",
		department: "",
		branch: "",
	});
	const [errors, setErrors] = useState<Record<string, string>>({});
	const [created, setCreated] = useState<CreatedCredentials | null>(null);

	const mutation = useMutation({
		mutationFn: () =>
			attacheeApi.createAttachee({
				first_name: form.first_name.trim(),
				last_name: form.last_name.trim(),
				email: form.email.trim().toLowerCase(),
				phone: form.phone.trim() || undefined,
				department: form.department || undefined,
				branch: form.branch || undefined,
			}),
		onSuccess: (data) => {
			setCreated(data);
			qc.invalidateQueries({ queryKey: ["users", "attachee"] });
		},
		onError: (err: any) => {
			const msg =
				err?.response?.data?.detail ??
				"Could not create account. Check the details and try again.";
			toast.error(msg);
		},
	});

	const validate = () => {
		const e: Record<string, string> = {};
		if (!form.first_name.trim()) e.first_name = "First name is required";
		if (!form.email.trim()) e.email = "Email is required";
		else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))
			e.email = "Invalid email address";
		setErrors(e);
		return Object.keys(e).length === 0;
	};

	const handleSubmit = () => {
		if (validate()) mutation.mutate();
	};

	const handleClose = () => {
		setCreated(null);
		onClose();
	};

	return (
		<div className="modal-backdrop" onClick={handleClose}>
			<div
				className="modal-box max-w-lg w-full"
				onClick={(e) => e.stopPropagation()}>
				{/* Header */}
				<div className="modal-header">
					<h3 className="font-semibold text-white flex items-center gap-2">
						<GraduationCap size={16} className="text-blue-400" />
						{created ? "Attachee onboarded" : "Add new attachee"}
					</h3>
					<button onClick={handleClose} className="btn-ghost p-1.5">
						<X size={14} />
					</button>
				</div>

				{created ? (
					/* ── Success screen ── */
					<div className="modal-body space-y-4">
						<div className="flex items-center gap-3 p-4 bg-green-500/10 border border-green-500/20 rounded-xl">
							<CheckCircle2 size={20} className="text-green-400 shrink-0" />
							<div>
								<div className="text-sm font-semibold text-white">
									{created.full_name} has been onboarded
								</div>
								<div className="text-xs text-slate-400 mt-0.5">
									Login credentials have been emailed. They must change their
									password on first login.
								</div>
							</div>
						</div>

						<div className="space-y-2">
							<CredentialRow label="Email / Username" value={created.email} />
							<CredentialRow
								label="Employee ID"
								value={created.employee_id}
								mono
							/>
							<CredentialRow
								label="Temporary Password"
								value={created.temp_password}
								mono
							/>
						</div>

						<div className="flex items-center gap-2 p-3 bg-blue-500/5 border border-blue-500/10 rounded-xl">
							<Mail size={13} className="text-blue-400 shrink-0" />
							<p className="text-xs text-slate-400">
								These credentials have been sent to{" "}
								<span className="text-white">{created.email}</span>
							</p>
						</div>

						<div className="flex justify-end gap-3 pt-1">
							<button
								onClick={() => setCreated(null)}
								className="btn-secondary btn-sm">
								<UserPlus size={13} /> Add another
							</button>
							<button onClick={handleClose} className="btn-primary btn-sm">
								Done
							</button>
						</div>
					</div>
				) : (
					/* ── Form ── */
					<div className="modal-body space-y-4">
						{/* Info banner */}
						<div className="flex items-start gap-2 p-3 bg-slate-500/10 border border-white/5 rounded-xl text-xs text-slate-400">
							<Shield size={13} className="text-blue-400 mt-0.5 shrink-0" />
							<span>
								Password and Employee ID are{" "}
								<span className="text-white font-medium">auto-generated</span>{" "}
								and emailed to the attachee. They will be prompted to change
								their password on first login.
							</span>
						</div>

						{/* Name row */}
						<div className="grid grid-cols-2 gap-4">
							<div>
								<label className="block text-xs text-slate-400 mb-1.5">
									First name <span className="text-red-400">*</span>
								</label>
								<input
									value={form.first_name}
									onChange={(e) =>
										setForm((f) => ({ ...f, first_name: e.target.value }))
									}
									className={clsx(
										"input w-full",
										errors.first_name && "border-red-500/50",
									)}
									placeholder="Jane"
								/>
								{errors.first_name && (
									<p className="text-[11px] text-red-400 mt-1">
										{errors.first_name}
									</p>
								)}
							</div>
							<div>
								<label className="block text-xs text-slate-400 mb-1.5">
									Last name
								</label>
								<input
									value={form.last_name}
									onChange={(e) =>
										setForm((f) => ({ ...f, last_name: e.target.value }))
									}
									className="input w-full"
									placeholder="Muthoni"
								/>
							</div>
						</div>

						{/* Email */}
						<div>
							<label className="block text-xs text-slate-400 mb-1.5">
								Email address <span className="text-red-400">*</span>
							</label>
							<input
								type="email"
								value={form.email}
								onChange={(e) =>
									setForm((f) => ({ ...f, email: e.target.value }))
								}
								className={clsx(
									"input w-full",
									errors.email && "border-red-500/50",
								)}
								placeholder="jane@example.com"
							/>
							{errors.email && (
								<p className="text-[11px] text-red-400 mt-1">{errors.email}</p>
							)}
						</div>

						{/* Phone + Department */}
						<div className="grid grid-cols-2 gap-4">
							<div>
								<label className="block text-xs text-slate-400 mb-1.5">
									Phone (optional)
								</label>
								<input
									type="tel"
									value={form.phone}
									onChange={(e) =>
										setForm((f) => ({ ...f, phone: e.target.value }))
									}
									className="input w-full"
									placeholder="+254 700 000 000"
								/>
							</div>
							<div>
								<label className="block text-xs text-slate-400 mb-1.5">
									Department
								</label>
								<select
									value={form.department}
									onChange={(e) =>
										setForm((f) => ({ ...f, department: e.target.value }))
									}
									className="select-input w-full">
									<option value="">— Select —</option>
									{departments.map((d) => (
										<option key={d.id} value={d.id}>
											{d.name}
										</option>
									))}
								</select>
							</div>
						</div>

						{/* Branch */}
						<div>
							<label className="block text-xs text-slate-400 mb-1.5">
								Branch (optional)
							</label>
							<select
								value={form.branch}
								onChange={(e) =>
									setForm((f) => ({ ...f, branch: e.target.value }))
								}
								className="select-input w-full">
								<option value="">— Select branch —</option>
								{branches.map((b) => (
									<option key={b.id} value={b.id}>
										{b.name}
									</option>
								))}
							</select>
						</div>

						{/* Actions */}
						<div className="flex justify-end gap-3 pt-1">
							<button onClick={handleClose} className="btn-secondary btn-sm">
								Cancel
							</button>
							<button
								onClick={handleSubmit}
								disabled={mutation.isPending}
								className="btn-primary btn-sm">
								{mutation.isPending ? (
									<>
										<Loader2 size={13} className="animate-spin" /> Creating…
									</>
								) : (
									<>
										<GraduationCap size={13} /> Onboard attachee
									</>
								)}
							</button>
						</div>
					</div>
				)}
			</div>
		</div>
	);
}

// ── Import Preview Modal ──────────────────────────────────────────────────────

function ImportPreviewModal({
	rows,
	onClose,
	onCommit,
	committing,
}: {
	rows: PreviewRow[];
	onClose: () => void;
	onCommit: (selected: PreviewRow[]) => void;
	committing: boolean;
}) {
	const [selected, setSelected] = useState<Set<number>>(
		() =>
			new Set(rows.filter((r) => r.status === "valid").map((r) => r._rowIndex)),
	);
	const [search, setSearch] = useState("");
	const [statusFilter, setStatusFilter] = useState<
		"all" | "valid" | "duplicate" | "invalid"
	>("all");
	const [deptFilter, setDeptFilter] = useState("");

	const departments = useMemo(() => {
		const depts = new Set(rows.map((r) => r.department).filter(Boolean));
		return Array.from(depts) as string[];
	}, [rows]);

	const filtered = useMemo(() => {
		return rows.filter((r) => {
			if (statusFilter !== "all" && r.status !== statusFilter) return false;
			if (deptFilter && r.department !== deptFilter) return false;
			if (search) {
				const q = search.toLowerCase();
				return (
					r.full_name.toLowerCase().includes(q) ||
					r.email.toLowerCase().includes(q)
				);
			}
			return true;
		});
	}, [rows, search, statusFilter, deptFilter]);

	const validRows = rows.filter((r) => r.status === "valid");
	const selectedCount = selected.size;
	const allFilteredValid = filtered.filter((r) => r.status === "valid");
	const allFilteredSelected =
		allFilteredValid.length > 0 &&
		allFilteredValid.every((r) => selected.has(r._rowIndex));

	const toggle = (idx: number) => {
		setSelected((prev) => {
			const next = new Set(prev);
			next.has(idx) ? next.delete(idx) : next.add(idx);
			return next;
		});
	};

	const toggleAllFiltered = () => {
		setSelected((prev) => {
			const next = new Set(prev);
			if (allFilteredSelected) {
				allFilteredValid.forEach((r) => next.delete(r._rowIndex));
			} else {
				allFilteredValid.forEach((r) => next.add(r._rowIndex));
			}
			return next;
		});
	};

	const selectAll = () =>
		setSelected(new Set(validRows.map((r) => r._rowIndex)));
	const clearAll = () => setSelected(new Set());

	const statusBadge = (r: PreviewRow) => {
		if (r.status === "valid")
			return <span className="badge badge-green text-[10px]">Valid</span>;
		if (r.status === "duplicate")
			return <span className="badge badge-yellow text-[10px]">Duplicate</span>;
		return <span className="badge badge-red text-[10px]">Invalid</span>;
	};

	const counts = {
		valid: rows.filter((r) => r.status === "valid").length,
		duplicate: rows.filter((r) => r.status === "duplicate").length,
		invalid: rows.filter((r) => r.status === "invalid").length,
	};

	return (
		<div className="modal-backdrop" onClick={onClose}>
			<div
				className="modal-box w-full max-w-4xl flex flex-col"
				style={{ maxHeight: "90vh" }}
				onClick={(e) => e.stopPropagation()}>
				{/* Header */}
				<div className="modal-header shrink-0">
					<h3 className="font-semibold text-white flex items-center gap-2">
						<FileSpreadsheet size={16} className="text-blue-400" />
						Preview Import
						<span className="text-slate-500 font-normal text-sm ml-1">
							{rows.length} row{rows.length !== 1 ? "s" : ""} found
						</span>
					</h3>
					<button onClick={onClose} className="btn-ghost p-1.5">
						<X size={14} />
					</button>
				</div>

				{/* Info banner — auto-generated credentials */}
				<div className="shrink-0 mx-5 mt-3 flex items-start gap-2 p-3 bg-blue-500/5 border border-blue-500/10 rounded-xl text-xs text-slate-400">
					<Shield size={13} className="text-blue-400 mt-0.5 shrink-0" />
					<span>
						Password and Employee ID are{" "}
						<span className="text-white font-medium">auto-generated</span> for
						each row and emailed directly to the new account. You do not need to
						include them in your file.
					</span>
				</div>

				{/* Summary bar */}
				<div className="shrink-0 px-5 py-3 flex flex-wrap gap-4 border-b border-white/5 bg-surface/40 mt-3">
					{[
						{
							label: "Valid",
							count: counts.valid,
							color: "text-green-400",
							key: "valid",
						},
						{
							label: "Duplicates",
							count: counts.duplicate,
							color: "text-yellow-400",
							key: "duplicate",
						},
						{
							label: "Invalid",
							count: counts.invalid,
							color: "text-red-400",
							key: "invalid",
						},
					].map((s) => (
						<button
							key={s.key}
							onClick={() =>
								setStatusFilter(
									statusFilter === (s.key as any) ? "all" : (s.key as any),
								)
							}
							className={clsx(
								"flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors",
								statusFilter === s.key
									? "bg-white/10 text-white"
									: "text-slate-400 hover:text-white",
							)}>
							<span className={clsx("text-sm font-bold", s.color)}>
								{s.count}
							</span>
							{s.label}
						</button>
					))}
					<div className="ml-auto flex items-center gap-2 text-xs text-slate-400">
						<Users size={13} />
						<span>
							<span className="text-white font-semibold">{selectedCount}</span>{" "}
							selected
						</span>
					</div>
				</div>

				{/* Filters */}
				<div className="shrink-0 px-5 py-3 flex flex-wrap gap-3 border-b border-white/5">
					<div className="relative flex-1 min-w-40">
						<Search
							size={13}
							className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"
						/>
						<input
							value={search}
							onChange={(e) => setSearch(e.target.value)}
							placeholder="Search name or email…"
							className="input pl-8 py-1.5 text-sm"
						/>
					</div>
					{departments.length > 0 && (
						<select
							value={deptFilter}
							onChange={(e) => setDeptFilter(e.target.value)}
							className="select-input w-44 text-sm">
							<option value="">All Departments</option>
							{departments.map((d) => (
								<option key={d} value={d}>
									{d}
								</option>
							))}
						</select>
					)}
					<button
						onClick={toggleAllFiltered}
						className="btn-secondary btn-sm text-xs">
						{allFilteredSelected ? (
							<Square size={12} />
						) : (
							<SquareCheck size={12} />
						)}
						{allFilteredSelected ? "Deselect visible" : "Select visible"}
					</button>
					<button onClick={selectAll} className="btn-secondary btn-sm text-xs">
						Select all valid
					</button>
					<button
						onClick={clearAll}
						className="btn-secondary btn-sm text-xs text-slate-400">
						Clear all
					</button>
				</div>

				{/* Table */}
				<div className="flex-1 overflow-y-auto min-h-0">
					<table className="data-table text-sm">
						<thead>
							<tr>
								<th className="w-8"></th>
								<th>Name</th>
								<th>Email</th>
								<th>Phone</th>
								<th>Department</th>
								<th>Branch</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>
							{filtered.length === 0 ? (
								<tr>
									<td colSpan={7} className="text-center py-10 text-slate-500">
										No rows match your filters
									</td>
								</tr>
							) : (
								filtered.map((r) => {
									const isSelected = selected.has(r._rowIndex);
									const isSelectable = r.status === "valid";
									return (
										<tr
											key={r._rowIndex}
											onClick={() => isSelectable && toggle(r._rowIndex)}
											className={clsx(
												"transition-colors",
												isSelectable
													? "cursor-pointer"
													: "opacity-40 cursor-not-allowed",
												isSelected && "bg-blue-500/5",
											)}>
											<td onClick={(e) => e.stopPropagation()}>
												<input
													type="checkbox"
													checked={isSelected}
													disabled={!isSelectable}
													onChange={() => isSelectable && toggle(r._rowIndex)}
													className="accent-blue-500 w-3.5 h-3.5 cursor-pointer"
												/>
											</td>
											<td>
												<div className="font-medium text-white">
													{r.full_name || "—"}
												</div>
											</td>
											<td className="text-slate-400 text-xs">{r.email}</td>
											<td className="text-slate-400 text-xs">
												{r.phone || "—"}
											</td>
											<td className="text-slate-400 text-xs">
												{r.department || "—"}
											</td>
											<td className="text-slate-400 text-xs">
												{r.branch || "—"}
											</td>
											<td>
												<div className="space-y-0.5">
													{statusBadge(r)}
													{r.statusReason && (
														<div className="text-[10px] text-slate-500">
															{r.statusReason}
														</div>
													)}
												</div>
											</td>
										</tr>
									);
								})
							)}
						</tbody>
					</table>
				</div>

				{/* Footer */}
				<div className="shrink-0 modal-footer border-t border-white/5">
					<div className="flex items-center gap-2 mr-auto text-xs text-slate-400">
						<Mail size={13} className="text-blue-400" />
						Credentials emailed to each new account automatically
					</div>
					<button onClick={onClose} className="btn-secondary btn-sm">
						Cancel
					</button>
					<button
						onClick={() => {
							const toImport = rows.filter(
								(r) => selected.has(r._rowIndex) && r.status === "valid",
							);
							if (toImport.length === 0) {
								toast.error("No valid rows selected");
								return;
							}
							onCommit(toImport);
						}}
						disabled={committing || selectedCount === 0}
						className="btn-primary btn-sm">
						{committing ? (
							<>
								<Loader2 size={13} className="animate-spin" /> Importing…
							</>
						) : (
							<>
								<CheckCircle size={13} /> Import {selectedCount} attachee
								{selectedCount !== 1 ? "s" : ""}
							</>
						)}
					</button>
				</div>
			</div>
		</div>
	);
}

// ── Import Result Modal ───────────────────────────────────────────────────────

function ImportResultModal({
	result,
	onClose,
}: {
	result: ImportResult;
	onClose: () => void;
}) {
	const [tab, setTab] = useState<
		"created" | "duplicates" | "skipped" | "errors"
	>("created");
	const tabs = [
		{
			key: "created" as const,
			label: "Created",
			count: result.summary.created,
			color: "text-green-400",
		},
		{
			key: "duplicates" as const,
			label: "Duplicates",
			count: result.summary.duplicates,
			color: "text-yellow-400",
		},
		{
			key: "skipped" as const,
			label: "Skipped",
			count: result.summary.skipped,
			color: "text-slate-400",
		},
		{
			key: "errors" as const,
			label: "Errors",
			count: result.summary.errors,
			color: "text-red-400",
		},
	] as const;

	return (
		<div className="modal-backdrop" onClick={onClose}>
			<div
				className="modal-box max-w-2xl w-full"
				onClick={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<h3 className="font-semibold text-white flex items-center gap-2">
						<CheckCircle size={16} className="text-green-400" />
						Import Complete
					</h3>
					<button onClick={onClose} className="btn-ghost p-1.5">
						<X size={14} />
					</button>
				</div>

				{result.summary.created > 0 && (
					<div className="mx-5 mt-4 p-3 rounded-xl bg-green-500/10 border border-green-500/20 flex items-center gap-3">
						<Mail size={16} className="text-green-400 shrink-0" />
						<p className="text-sm text-green-300">
							Credentials emailed to{" "}
							<span className="font-semibold">{result.summary.created}</span>{" "}
							new account{result.summary.created !== 1 ? "s" : ""}. Each person
							will be prompted to set a new password on first login.
						</p>
					</div>
				)}

				<div className="px-5 py-3 flex flex-wrap gap-3 border-b border-white/5 mt-3">
					{tabs.map((t) => (
						<button
							key={t.key}
							onClick={() => setTab(t.key)}
							className={clsx(
								"px-3 py-1.5 rounded-lg text-xs font-medium transition-colors",
								tab === t.key
									? "bg-white/10 text-white"
									: "text-slate-500 hover:text-slate-300",
							)}>
							<span className={t.color}>{t.count}</span> {t.label}
						</button>
					))}
				</div>

				<div className="modal-body max-h-72 overflow-y-auto space-y-1">
					{tab === "created" &&
						(result.created.length === 0 ? (
							<p className="text-slate-500 text-sm text-center py-6">
								No records created.
							</p>
						) : (
							result.created.map((r, i) => (
								<div
									key={i}
									className="flex items-center gap-3 py-2 px-3 rounded-lg bg-green-500/5 border border-green-500/10">
									<CheckCircle size={13} className="text-green-400 shrink-0" />
									<div className="min-w-0 flex-1">
										<div className="text-sm text-white font-medium truncate">
											{r.full_name}
										</div>
										<div className="text-xs text-slate-500 truncate">
											{r.email}
											{r.employee_id ? ` · ${r.employee_id}` : ""}
											{r.department ? ` · ${r.department}` : ""}
										</div>
									</div>
									<Mail
										size={12}
										className="text-blue-400 shrink-0"
									/>
								</div>
							))
						))}

					{tab === "duplicates" &&
						(result.duplicates.length === 0 ? (
							<p className="text-slate-500 text-sm text-center py-6">
								No duplicates.
							</p>
						) : (
							result.duplicates.map((r, i) => (
								<div
									key={i}
									className="py-2 px-3 rounded-lg bg-yellow-500/5 border border-yellow-500/10">
									<div className="flex items-center gap-2">
										<AlertCircle
											size={13}
											className="text-yellow-400 shrink-0"
										/>
										<span className="text-sm text-white">{r.email}</span>
										{r.is_active !== undefined && (
											<span
												className={clsx(
													"badge ml-auto",
													r.is_active ? "badge-green" : "badge-slate",
												)}>
												{r.is_active ? "Active" : "Inactive"}
											</span>
										)}
									</div>
									<p className="text-xs text-yellow-300/70 ml-5 mt-0.5">
										{r.message}
									</p>
								</div>
							))
						))}

					{tab === "skipped" &&
						(result.skipped.length === 0 ? (
							<p className="text-slate-500 text-sm text-center py-6">
								No rows skipped.
							</p>
						) : (
							result.skipped.map((r, i) => (
								<div
									key={i}
									className="py-2 px-3 rounded-lg bg-slate-500/5 border border-white/5">
									<div className="flex items-center gap-2">
										<Info size={13} className="text-slate-400 shrink-0" />
										<span className="text-xs text-slate-400">
											Row {r.row} · {r.email}
										</span>
									</div>
									<p className="text-xs text-slate-500 ml-5">{r.reason}</p>
								</div>
							))
						))}

					{tab === "errors" &&
						(result.errors.length === 0 ? (
							<p className="text-slate-500 text-sm text-center py-6">
								No errors.
							</p>
						) : (
							result.errors.map((r, i) => (
								<div
									key={i}
									className="py-2 px-3 rounded-lg bg-red-500/5 border border-red-500/10">
									<div className="flex items-center gap-2">
										<AlertTriangle
											size={13}
											className="text-red-400 shrink-0"
										/>
										<span className="text-xs text-slate-300">
											Row {r.row} · {r.email}
										</span>
									</div>
									<p className="text-xs text-red-300/70 ml-5">{r.reason}</p>
								</div>
							))
						))}
				</div>

				<div className="modal-footer">
					<button onClick={onClose} className="btn-primary btn-sm">
						Done
					</button>
				</div>
			</div>
		</div>
	);
}

// ── Assign Supervisor Modal ───────────────────────────────────────────────────

function AssignSupervisorModal({
	attachee,
	supervisors,
	onClose,
	onAssign,
	onDeassign,
	loading,
}: {
	attachee: Attachee;
	supervisors: Supervisor[];
	onClose: () => void;
	onAssign: (supervisorId: string) => void;
	onDeassign: () => void;
	loading: boolean;
}) {
	const [selected, setSelected] = useState(attachee.supervisor_user ?? "");

	return (
		<div className="modal-backdrop" onClick={onClose}>
			<div className="modal-box max-w-md" onClick={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<h3 className="font-semibold text-white flex items-center gap-2">
						<UserCheck size={15} className="text-blue-400" /> Assign Supervisor
					</h3>
					<button onClick={onClose} className="btn-ghost p-1.5">
						<X size={14} />
					</button>
				</div>
				<div className="modal-body space-y-4">
					<div className="flex items-center gap-3 p-3 bg-surface rounded-xl">
						<div className="w-9 h-9 rounded-full bg-gradient-Swahilipot flex items-center justify-center text-xs font-bold text-white shrink-0">
							{attachee.full_name
								?.split(" ")
								.map((n) => n[0])
								.join("")
								.slice(0, 2)}
						</div>
						<div>
							<div className="text-white text-sm font-medium">
								{attachee.full_name}
							</div>
							<div className="text-xs text-slate-500">{attachee.email}</div>
						</div>
						{attachee.supervisor_name && (
							<div className="ml-auto text-right">
								<div className="text-xs text-slate-500">Current</div>
								<div className="text-xs text-blue-400 font-medium">
									{attachee.supervisor_name}
								</div>
							</div>
						)}
					</div>
					<div>
						<label className="block text-xs text-slate-400 mb-1.5">
							Select supervisor
						</label>
						<select
							value={selected}
							onChange={(e) => setSelected(e.target.value)}
							className="select-input w-full">
							<option value="">— Choose a supervisor —</option>
							{supervisors.map((s) => (
								<option key={s.id} value={s.id}>
									{s.full_name}
									{s.department_name ? ` (${s.department_name})` : ""}
								</option>
							))}
						</select>
						{supervisors.length === 0 && (
							<p className="text-xs text-slate-500 mt-1.5">
								No supervisors found in your organisation.
							</p>
						)}
					</div>
				</div>
				<div className="modal-footer">
					{attachee.supervisor_user && (
						<button
							onClick={onDeassign}
							disabled={loading}
							className="btn-secondary btn-sm text-red-400 hover:text-red-300 mr-auto">
							{loading ? (
								<Loader2 size={13} className="animate-spin" />
							) : (
								<UserX size={13} />
							)}{" "}
							Remove
						</button>
					)}
					<button onClick={onClose} className="btn-secondary btn-sm">
						Cancel
					</button>
					<button
						onClick={() => selected && onAssign(selected)}
						disabled={!selected || loading}
						className="btn-primary btn-sm">
						{loading ? (
							<Loader2 size={13} className="animate-spin" />
						) : (
							<UserCheck size={13} />
						)}{" "}
						Assign
					</button>
				</div>
			</div>
		</div>
	);
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function AttacheeListPage() {
	const { user } = useAuthStore();
	const qc = useQueryClient();
	const fileRef = useRef<HTMLInputElement>(null);

	const [search, setSearch] = useState("");
	const [deptFilter, setDeptFilter] = useState("");
	const [statusFilter, setStatusFilter] = useState<"" | "active" | "inactive">(
		"",
	);
	const [selectedAttachee, setSelectedAttachee] = useState<Attachee | null>(
		null,
	);
	const [importResult, setImportResult] = useState<ImportResult | null>(null);
	const [previewRows, setPreviewRows] = useState<PreviewRow[] | null>(null);
	const [assignTarget, setAssignTarget] = useState<Attachee | null>(null);
	const [parsing, setParsing] = useState(false);
	const [showAddModal, setShowAddModal] = useState(false);

	const isAdmin = ["hr_officer", "system_admin", "executive"].includes(
		user?.role ?? "",
	);
	const isDeptLeader = user?.role === "department_leader";
	const canImport = isAdmin || isDeptLeader;
	const canManage = isAdmin || isDeptLeader;

	// ── Queries ───────────────────────────────────────────────────────────────
	const {
		data: attachees = [],
		isLoading,
		refetch,
	} = useQuery({
		queryKey: ["users", "attachee", search, deptFilter, statusFilter],
		queryFn: () =>
			usersApi
				.list({
					role: "attachee",
					search: search || undefined,
					department: deptFilter || undefined,
					is_active:
						statusFilter === "active"
							? true
							: statusFilter === "inactive"
								? false
								: undefined,
				})
				.then((r) => r.data.results ?? r.data),
		refetchInterval: 120_000,
	});

	const { data: departments = [] } = useQuery<Department[]>({
		queryKey: ["departments"],
		queryFn: () => hrApi.departments().then((r) => r.data.results ?? r.data),
	});

	const { data: branches = [] } = useQuery<Branch[]>({
		queryKey: ["branches"],
		queryFn: () => hrApi.branches().then((r) => r.data.results ?? r.data),
	});

	const { data: supervisors = [] } = useQuery<Supervisor[]>({
		queryKey: ["supervisors"],
		queryFn: () =>
			usersApi
				.list({ role: "supervisor" })
				.then((r) => r.data.results ?? r.data),
		enabled: canManage,
	});

	// ── Mutations ─────────────────────────────────────────────────────────────
	const commitMutation = useMutation({
		mutationFn: attacheeApi.commitImport,
		onSuccess: (data) => {
			setPreviewRows(null);
			setImportResult(data);
			qc.invalidateQueries({ queryKey: ["users", "attachee"] });
			if (data.summary.created > 0)
				toast.success(
					`${data.summary.created} attachee${data.summary.created > 1 ? "s" : ""} created & emailed`,
				);
			if (data.summary.duplicates > 0)
				toast(
					`${data.summary.duplicates} duplicate${data.summary.duplicates > 1 ? "s" : ""} skipped`,
					{ icon: "⚠️" },
				);
		},
		onError: (err: any) => {
			const msg =
				err?.response?.data?.detail ?? "Import failed. Please try again.";
			toast.error(msg);
		},
	});

	const assignMutation = useMutation({
		mutationFn: ({ id, sid }: { id: string; sid: string }) =>
			attacheeApi.assignSupervisor(id, sid),
		onSuccess: () => {
			toast.success("Supervisor assigned");
			qc.invalidateQueries({ queryKey: ["users", "attachee"] });
			setAssignTarget(null);
		},
		onError: () => toast.error("Could not assign supervisor"),
	});

	const deassignMutation = useMutation({
		mutationFn: (id: string) => attacheeApi.deassignSupervisor(id),
		onSuccess: () => {
			toast.success("Supervisor removed");
			qc.invalidateQueries({ queryKey: ["users", "attachee"] });
			setAssignTarget(null);
		},
		onError: () => toast.error("Could not remove supervisor"),
	});

	const toggleMutation = useMutation({
		mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) =>
			attacheeApi.toggleActive(id, isActive),
		onSuccess: (_, vars) => {
			toast.success(`Account ${vars.isActive ? "activated" : "deactivated"}`);
			qc.invalidateQueries({ queryKey: ["users", "attachee"] });
			setSelectedAttachee(null);
		},
		onError: () => toast.error("Could not update account status"),
	});

	// ── File handler ──────────────────────────────────────────────────────────
	const handleFileChange = useCallback(
		async (e: React.ChangeEvent<HTMLInputElement>) => {
			const f = e.target.files?.[0];
			if (!f) return;
			if (!/\.(csv|xlsx|xls)$/i.test(f.name)) {
				toast.error("Please upload a .csv or .xlsx file");
				return;
			}
			setParsing(true);
			try {
				const rows = await parseFilePreview(f);
				if (rows.length === 0) {
					toast.error("File is empty or has no data rows");
					return;
				}
				setPreviewRows(rows);
			} catch {
				toast.error("Could not parse file. Check the format and try again.");
			} finally {
				setParsing(false);
				e.target.value = "";
			}
		},
		[],
	);

	// ── Stats ─────────────────────────────────────────────────────────────────
	const now = new Date();
	const thisMonthCount = (attachees as Attachee[]).filter((a) => {
		if (!a.date_joined) return false;
		const d = parseISO(a.date_joined);
		return (
			d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
		);
	}).length;

	const stats = [
		{
			label: "Total",
			value: (attachees as Attachee[]).length,
			color: "text-white",
		},
		{
			label: "Active",
			value: (attachees as Attachee[]).filter((a) => a.is_active).length,
			color: "text-green-400",
		},
		{
			label: "Inactive",
			value: (attachees as Attachee[]).filter((a) => !a.is_active).length,
			color: "text-red-400",
		},
		{ label: "This Month", value: thisMonthCount, color: "text-blue-400" },
	];

	return (
		<div className="space-y-6 animate-fade-in">
			{/* ── Header ── */}
			<div className="page-header">
				<div>
					<h1 className="page-title flex items-center gap-2">
						<GraduationCap size={22} className="text-Swahilipot-400" />
						Attachee Management
					</h1>
					<p className="page-subtitle">
						Placements, progress, and department assignments
					</p>
				</div>

				<div className="flex flex-wrap gap-2">
					{canImport && (
						<>
							<button
								onClick={attacheeApi.downloadTemplate}
								className="btn-secondary btn-sm"
								title="Download import template (CSV)">
								<Download size={13} /> Template
							</button>
							
							<Link to="/attachees/collect" className="btn-secondary btn-sm">
								<FileSpreadsheet size={13} /> Collect data
							</Link>
							
							<button
								onClick={() => fileRef.current?.click()}
								disabled={parsing || commitMutation.isPending}
								className="btn-secondary btn-sm">
								{parsing ? (
									<Loader2 size={13} className="animate-spin" />
								) : (
									<Upload size={13} />
								)}
								{parsing ? "Reading file…" : "Bulk Import CSV"}
							</button>
							<input
								ref={fileRef}
								type="file"
								accept=".csv,.xlsx,.xls"
								className="hidden"
								onChange={handleFileChange}
							/>
						</>
					)}
					{isAdmin && (
						<button
							onClick={() => setShowAddModal(true)}
							className="btn-primary btn-sm">
							<UserPlus size={13} /> Add Attachee
						</button>
					)}
				</div>
			</div>

			{/* ── Stats ── */}
			<div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
				{stats.map(({ label, value, color }) => (
					<div key={label} className="stat-card">
						<div className={clsx("stat-value", color)}>{value}</div>
						<div className="stat-label">{label}</div>
					</div>
				))}
			</div>

			{/* ── Filters ── */}
			<div className="flex flex-wrap gap-3">
				<div className="relative flex-1 min-w-48">
					<Search
						size={14}
						className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"
					/>
					<input
						value={search}
						onChange={(e) => setSearch(e.target.value)}
						placeholder="Search by name or email…"
						className="input pl-9 py-2"
					/>
				</div>
				<select
					value={deptFilter}
					onChange={(e) => setDeptFilter(e.target.value)}
					className="select-input w-44">
					<option value="">All Departments</option>
					{(departments as Department[]).map((d) => (
						<option key={d.id} value={d.id}>
							{d.name}
						</option>
					))}
				</select>
				<select
					value={statusFilter}
					onChange={(e) => setStatusFilter(e.target.value as any)}
					className="select-input w-36">
					<option value="">All Status</option>
					<option value="active">Active</option>
					<option value="inactive">Inactive</option>
				</select>
				<button
					onClick={() => refetch()}
					className="btn-secondary btn-sm px-2.5"
					title="Refresh">
					<RefreshCw size={13} />
				</button>
			</div>

			{/* ── Table ── */}
			<div className="card">
				<div className="overflow-x-auto">
					<table className="data-table">
						<thead>
							<tr>
								<th>Attachee</th>
								<th>Employee ID</th>
								<th>Department</th>
								<th>Branch</th>
								<th>Supervisor</th>
								<th>Status</th>
								<th>Date Joined</th>
								{canManage && <th>Actions</th>}
							</tr>
						</thead>
						<tbody>
							{isLoading ? (
								[...Array(8)].map((_, i) => (
									<tr key={i}>
										<td colSpan={8}>
											<div className="skeleton h-8 w-full my-1" />
										</td>
									</tr>
								))
							) : (attachees as Attachee[]).length === 0 ? (
								<tr>
									<td colSpan={8} className="text-center py-12 text-slate-500">
										<GraduationCap
											size={28}
											className="mx-auto mb-2 opacity-30"
										/>
										No attachees found
									</td>
								</tr>
							) : (
								(attachees as Attachee[]).map((a) => (
									<tr key={a.id} className={clsx(!a.is_active && "opacity-50")}>
										<td>
											<div className="flex items-center gap-3">
												<div className="w-8 h-8 rounded-full bg-gradient-Swahilipot flex items-center justify-center text-xs font-bold text-white shrink-0">
													{a.full_name
														?.split(" ")
														.map((n) => n[0])
														.join("")
														.slice(0, 2)}
												</div>
												<div>
													<div className="font-medium text-white text-sm">
														{a.full_name}
													</div>
													<div className="text-xs text-slate-500">
														{a.email}
													</div>
												</div>
											</div>
										</td>
										<td className="font-mono text-xs text-slate-400">
											{a.employee_id || "—"}
										</td>
										<td className="text-slate-300 text-sm">
											{a.department_name || "—"}
										</td>
										<td className="text-slate-400 text-sm">
											{a.branch_name || "—"}
										</td>
										<td className="text-slate-400 text-sm">
											{a.supervisor_name ? (
												<span className="flex items-center gap-1.5">
													<UserCheck size={11} className="text-blue-400" />
													{a.supervisor_name}
												</span>
											) : (
												<span className="text-slate-600 text-xs">
													Unassigned
												</span>
											)}
										</td>
										<td>
											<span
												className={clsx(
													"badge",
													a.is_active ? "badge-green" : "badge-slate",
												)}>
												{a.is_active ? "Active" : "Inactive"}
											</span>
										</td>
										<td className="text-slate-400 text-xs">
											{a.date_joined
												? format(parseISO(a.date_joined), "dd MMM yyyy")
												: "—"}
										</td>
										{canManage && (
											<td>
												<div className="flex items-center gap-1">
													<button
														onClick={() => setSelectedAttachee(a)}
														className="btn-ghost btn-sm p-1.5"
														title="View profile">
														<Eye size={13} />
													</button>
													<button
														onClick={() => setAssignTarget(a)}
														className="btn-ghost btn-sm p-1.5"
														title="Assign supervisor">
														<UserCheck
															size={13}
															className={
																a.supervisor_user ? "text-blue-400" : ""
															}
														/>
													</button>
													<button
														onClick={() =>
															toggleMutation.mutate({
																id: a.id,
																isActive: !a.is_active,
															})
														}
														disabled={toggleMutation.isPending}
														className="btn-ghost btn-sm p-1.5"
														title={
															a.is_active
																? "Deactivate account"
																: "Activate account"
														}>
														{a.is_active ? (
															<ShieldOff size={13} className="text-red-400" />
														) : (
															<ShieldCheck
																size={13}
																className="text-green-400"
															/>
														)}
													</button>
												</div>
											</td>
										)}
									</tr>
								))
							)}
						</tbody>
					</table>
				</div>
			</div>

			{/* ── Detail panel ── */}
			{selectedAttachee && (
				<div
					className="modal-backdrop"
					onClick={() => setSelectedAttachee(null)}>
					<div
						className="modal-box max-w-md"
						onClick={(e) => e.stopPropagation()}>
						<div className="modal-header">
							<h3 className="font-semibold text-white">Attachee Profile</h3>
							<button
								onClick={() => setSelectedAttachee(null)}
								className="btn-ghost p-1.5">
								<X size={14} />
							</button>
						</div>
						<div className="modal-body space-y-4">
							<div className="flex items-center gap-4">
								<div className="w-16 h-16 rounded-2xl bg-gradient-Swahilipot flex items-center justify-center text-xl font-bold text-white">
									{selectedAttachee.full_name
										?.split(" ")
										.map((n) => n[0])
										.join("")
										.slice(0, 2)}
								</div>
								<div>
									<div className="text-white font-semibold text-lg">
										{selectedAttachee.full_name}
									</div>
									<div className="text-slate-400 text-sm">
										{selectedAttachee.email}
									</div>
									<span
										className={clsx(
											"badge mt-1",
											selectedAttachee.is_active
												? "badge-green"
												: "badge-slate",
										)}>
										{selectedAttachee.is_active ? "Active" : "Inactive"}
									</span>
								</div>
							</div>
							<div className="grid grid-cols-2 gap-3 text-sm">
								{[
									["Department", selectedAttachee.department_name || "—"],
									["Branch", selectedAttachee.branch_name || "—"],
									["Employee ID", selectedAttachee.employee_id || "—"],
									[
										"Joined",
										selectedAttachee.date_joined
											? format(
													parseISO(selectedAttachee.date_joined),
													"dd MMM yyyy",
												)
											: "—",
									],
									["Phone", selectedAttachee.phone || "—"],
									[
										"Supervisor",
										selectedAttachee.supervisor_name || "Unassigned",
									],
									[
										"Last Active",
										selectedAttachee.last_login
											? format(
													parseISO(selectedAttachee.last_login),
													"dd MMM HH:mm",
												)
											: "Never",
									],
								].map(([label, value]) => (
									<div key={label} className="bg-surface rounded-lg p-3">
										<div className="text-slate-500 text-xs mb-0.5">{label}</div>
										<div className="text-white font-medium truncate">
											{value}
										</div>
									</div>
								))}
							</div>
						</div>
						<div className="modal-footer flex-wrap gap-2">
							<button
								onClick={() => setSelectedAttachee(null)}
								className="btn-secondary btn-sm">
								Close
							</button>
							{canManage && (
								<>
									<button
										onClick={() => {
											setAssignTarget(selectedAttachee);
											setSelectedAttachee(null);
										}}
										className="btn-secondary btn-sm">
										<UserCheck size={13} /> Supervisor
									</button>
									<button
										onClick={() =>
											toggleMutation.mutate({
												id: selectedAttachee.id,
												isActive: !selectedAttachee.is_active,
											})
										}
										disabled={toggleMutation.isPending}
										className={clsx(
											"btn-sm",
											selectedAttachee.is_active
												? "btn-secondary text-red-400"
												: "btn-primary",
										)}>
										{selectedAttachee.is_active ? (
											<>
												<ShieldOff size={13} /> Deactivate
											</>
										) : (
											<>
												<ShieldCheck size={13} /> Activate
											</>
										)}
									</button>
								</>
							)}
							<button className="btn-primary btn-sm ml-auto">
								<BarChart3 size={13} /> Progress
							</button>
						</div>
					</div>
				</div>
			)}

			{/* ── Add Attachee Modal ── */}
			{showAddModal && (
				<AddAttacheeModal
					departments={departments as Department[]}
					branches={branches as Branch[]}
					onClose={() => setShowAddModal(false)}
				/>
			)}

			{/* ── Import preview modal ── */}
			{previewRows && (
				<ImportPreviewModal
					rows={previewRows}
					committing={commitMutation.isPending}
					onClose={() => setPreviewRows(null)}
					onCommit={(selected) => commitMutation.mutate(selected)}
				/>
			)}

			{/* ── Import result modal ── */}
			{importResult && (
				<ImportResultModal
					result={importResult}
					onClose={() => setImportResult(null)}
				/>
			)}

			{/* ── Assign supervisor modal ── */}
			{assignTarget && (
				<AssignSupervisorModal
					attachee={assignTarget}
					supervisors={supervisors}
					loading={assignMutation.isPending || deassignMutation.isPending}
					onClose={() => setAssignTarget(null)}
					onAssign={(sid) =>
						assignMutation.mutate({ id: assignTarget.id, sid })
					}
					onDeassign={() => deassignMutation.mutate(assignTarget.id)}
				/>
			)}
		</div>
	);
}
