# Generated by Django 6.0.6 on 2026-06-17 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orgpolicy'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterModelOptions(
            name='newsstoryversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterModelOptions(
            name='radiofrequency',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='radioshow',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='editorialcomment',
            name='action',
            field=models.CharField(blank=True, help_text='Status transition that triggered this comment, if any', max_length=30),
        ),
        migrations.AddField(
            model_name='editorialcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment URLs'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='broadcast_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_stories', to='news.radioslot'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='changes_requested_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-archive after this date', null=True),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='featured_image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='featured_image_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='read_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule publish for a future time', null=True),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='List of source references'),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary for listings / broadcast tease'),
        ),
        migrations.AddField(
            model_name='newsstoryversion',
            name='diff_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Optional JSON diff for tracking changes'),
        ),
        migrations.AddField(
            model_name='radiofrequency',
            name='colour',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AddField(
            model_name='radiofrequency',
            name='stream_url',
            field=models.URLField(blank=True, help_text='Live stream URL if available'),
        ),
        migrations.AddField(
            model_name='radioshow',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='radio/shows/'),
        ),
        migrations.AddField(
            model_name='radioshow',
            name='default_duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='radioshow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='co_presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_presenting_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='List of guest names/details'),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='show_plan_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radioslot',
            name='show_plan_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_show_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwaresubscription',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Audio Editing, Broadcast, Productivity', max_length=100),
        ),
        migrations.AddField(
            model_name='softwaresubscription',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwaresubscription',
            name='purchase_order_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwaresubscription',
            name='support_contact',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwaresubscription',
            name='support_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_categories', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='news.newscategory'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='newscategory',
            unique_together={('organisation', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='newsstoryversion',
            unique_together={('story', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='newsstory',
            index=models.Index(fields=['author', 'status'], name='news_newsst_author__1c6f53_idx'),
        ),
        migrations.AddIndex(
            model_name='newsstory',
            index=models.Index(fields=['is_breaking', 'status'], name='news_newsst_is_brea_8ef437_idx'),
        ),
        migrations.AddIndex(
            model_name='newsstory',
            index=models.Index(fields=['scheduled_publish_at'], name='news_newsst_schedul_1056a2_idx'),
        ),
        migrations.AddIndex(
            model_name='radioslot',
            index=models.Index(fields=['status'], name='news_radios_status_b86919_idx'),
        ),
    ]
