# Generated by Django 6.0.6 on 2026-06-15 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_permissions_voice_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the surrogate `id` column only if it still exists
        migrations.RunSQL(
            sql="""
                ALTER TABLE chat_userpresence
                DROP COLUMN IF EXISTS id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Make `user` the primary key only if it isn't already
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.table_constraints tc
                        JOIN information_schema.key_column_usage kcu
                          ON tc.constraint_name = kcu.constraint_name
                         AND tc.table_name = kcu.table_name
                        WHERE tc.constraint_type = 'PRIMARY KEY'
                          AND tc.table_name = 'chat_userpresence'
                          AND kcu.column_name = 'user_id'
                    ) THEN
                        ALTER TABLE chat_userpresence
                        ADD PRIMARY KEY (user_id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]