# Generated by Django 6.0.6 on 2026-06-15 12:35
# Edited: wrapped in SeparateDatabaseAndState because 0003 already performed
# the real DB changes (drop id column, set user as primary key) via raw SQL.
# Running RemoveField/AlterField normally here would try to DROP COLUMN id
# again and fail with "column does not exist".

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_userpresence_id_alter_userpresence_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userpresence',
                    name='id',
                ),
                migrations.AlterField(
                    model_name='userpresence',
                    name='user',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='presence',
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[],  # no-op: 0003's raw SQL already did this in the DB
        ),
    ]
